from datetime import date, timedelta # Corrected import for timedelta
import numpy as np

class OptionContract:
    '''期权合约表示'''
    def __init__(self, underlying_symbol: str, strike: float, expiry: date, option_type: str,
                 premium: float = 0.0, contract_id: int = 0, ib_contract = None): # ib_contract can store the ib_insync.Option object
        self.underlying_symbol = underlying_symbol # e.g., "QQQ"
        self.strike = strike
        self.expiry = expiry # Should be a datetime.date object
        self.option_type = option_type.upper()  # 'CALL' or 'PUT'
        self.premium = premium # Current market price of the option
        self.contract_id = contract_id # IBKR specific contract ID (conId)
        self.ib_contract = ib_contract # Store the full ib_insync contract object if available

        # Optional: Greeks can be added later if needed and fetched
        self.delta = np.nan
        self.gamma = np.nan
        self.theta = np.nan
        self.vega = np.nan

        # Symbol for the option itself (e.g., QQQ231231C00350000)
        # This can be constructed or obtained from IBKR
        self.symbol = self._generate_option_symbol()

    def _generate_option_symbol(self) -> str:
        """
        Generates a standard option symbol, e.g., QQQYYMMDDCPPPPPPP.
        This is a common representation but might differ from IBKR's specific localSymbol.
        """
        if not isinstance(self.expiry, date):
            # Attempt to convert if it's a string, though it should be date
            try:
                self.expiry = date.fromisoformat(str(self.expiry))
            except ValueError: # pragma: no cover
                 # Fallback or raise error if conversion fails
                return f"{self.underlying_symbol}{self.strike}{self.option_type[0]}"


        return (f"{self.underlying_symbol}"
                f"{self.expiry.strftime('%y%m%d')}"
                f"{self.option_type[0]}"
                f"{int(self.strike * 1000):08d}")


    def intrinsic_value(self, underlying_price: float) -> float:
        '''计算内在价值'''
        if self.option_type == 'CALL':
            return max(0.0, underlying_price - self.strike)
        elif self.option_type == 'PUT':
            return max(0.0, self.strike - underlying_price)
        return 0.0

    def time_value(self, underlying_price: float) -> float:
        '''计算时间价值'''
        # Ensure premium is positive, otherwise time value can be negative if ITM option premium is less than intrinsic
        current_premium = self.premium if self.premium > 0 else 0
        intrinsic = self.intrinsic_value(underlying_price)
        # Time value cannot be negative; if calculation results in negative, it's likely due to market pricing anomalies or stale premium data
        return max(0.0, current_premium - intrinsic)

    def is_itm(self, underlying_price: float) -> bool:
        '''Check if the option is In-The-Money (ITM)'''
        return self.intrinsic_value(underlying_price) > 0

    def days_to_expiry(self, current_date: date) -> int:
        '''Calculate days to expiry from a given date'''
        if not isinstance(self.expiry, date) or not isinstance(current_date, date): # pragma: no cover
            return -1 # Indicate error or unknown
        return (self.expiry - current_date).days

    def update_greeks(self, delta=np.nan, gamma=np.nan, theta=np.nan, vega=np.nan): # pragma: no cover
        """Method to update option's Greeks."""
        self.delta = delta
        self.gamma = gamma
        self.theta = theta
        self.vega = vega

    def __repr__(self):
        return (f"OptionContract(Symbol: {self.symbol}, Underlying: {self.underlying_symbol}, "
                f"Strike: {self.strike}, Expiry: {self.expiry.strftime('%Y-%m-%d')}, Type: {self.option_type}, "
                f"Premium: {self.premium:.2f}, ConID: {self.contract_id}, "
                f"ITM: {self.is_itm(self.premium + self.strike if self.option_type == 'CALL' else self.strike - self.premium )})") # Approximation for underlying for ITM check in repr
                # A more accurate ITM in repr would require passing underlying price

    def __str__(self):
        # Provides the standard OCC option symbol format, useful for systems expecting it.
        # Example: SPX   231215C04500000
        # Underlying (padded to 6 chars), YYMMDD, Type (C/P), Strike (8 digits, 3 decimal places)
        # This might need adjustment based on the exact format required by IBKR or other systems.
        # The self.symbol generated by _generate_option_symbol is often more practical.
        return self.symbol
